### ISSUE TITLE
User Story 3: Edit Bill

### ISSUE THREAD

**Issue by d-opri** [d-opri/Kroko-Capstone#10]
## Value Proposition

**As a** ... User
**I want to** ... be able to view my bill details
**so that** ... i can make changes 

## Description

![Frame 23411](https://user-images.githubusercontent.com/118123298/216996166-4d64950f-bf4c-4e84-9888-f5ee3b553aa2.png)

## Acceptance Criteria

- [ ] A Link to view details is displayed for each item
- [ ] the details are displayed on a new page
- [ ] an exit button navigates back to main
- [ ] an edit button opens edit mode for the bill
- [ ] changes can be made within inputs
- [ ] save changes will save and update the bill, and navigate back to main

## Tasks

- [ ] create link, details page, implement routing 
- [ ] create component to display content
- [ ] create button to exit and navigate to main
- [ ] create button to open edit option
- [ ] create button to save and update content
- [ ] use route to navigate back to main

## Complexity

... (m)
