### ISSUE TITLE
Delete Bill

### ISSUE THREAD

**Issue by d-opri** [d-opri/Kroko-Capstone#13]
## Value Proposition

**As a** ... User
**I want to** ... delete bills
**so that** ... i can remove bills
## Description

![Frame 23411](https://user-images.githubusercontent.com/118123298/218179415-2144b636-514a-4e44-bbb6-8c8b473c793b.png)

## Acceptance Criteria

- [ ] delete button displayed on bills details page
- [ ] on click will delete bill 
- [ ] and redirect to dashboard
- [ ] list item of bill is gone from list

## Tasks

- [ ] write helper function in db file and export
- [ ] write delete operation in handler file and import helper
- [ ] write fetcher function
- [ ] on bill details page: write async delete function to fetch data, then use method delete
- [ ] add button to call delete function

## Complexity

S

**Comment by Long-HaHoang** [comment]
Overall seems ok. The complexity seems a bit low. But maybe you already got it figured out.
