### ISSUE TITLE
User Story 2 Create a new Bill

### ISSUE THREAD

**Issue by d-opri** [d-opri/Kroko-Capstone#3]
## Value Proposition

As a user I want to create a bill so that I can keep track of shared expenses

## Description

![User Story 2](https://user-images.githubusercontent.com/118123298/213991765-d09534c4-506b-4e8d-80de-0e4f18d50953.jpg)

## Acceptance Criteria

- [ ] amount input is displayed
- [ ] title input is displayed
- [ ] add participants input with add button is displayed:
   - [ ] creates a list item
- [ ] participants list item is displayed with:
   - [ ] value of input
   - [ ] a radio button 
   - [ ] a delete button 
 - [ ] a subtitle displays "Paid By"

## Tasks

- [ ] create a Form Component
- [ ] create inputs for title, amount and participants with the correct input types
- [ ] create add participants button that renders a list item
- [ ] for the list item create:
   - [ ] a radio button to select "PaidBy"
   - [ ] a delete button that deletes the item 
- [ ] create a subtitle "paid by"

## Complexity

 M

**Comment by SaschaRadojkovic** [comment]
hi danie , does the radio button and the delete button have any functionality? if yes ,you should add the tasks for this if no maybe you should remove them ( i try to learn reading and understanding the userstorys and give my senf to it ;) )
