### ISSUE TITLE
User Story 3: Calculate Split

### ISSUE THREAD

**Issue by d-opri** [d-opri/Kroko-Capstone#5]
## Value Proposition

**As a** User
**I want to** calculate the split amount 
**so that** I can settle up   

## Description

![User Story 3](https://user-images.githubusercontent.com/118123298/215067917-34364af1-2944-4056-98c8-2814a772ef4f.jpg)

## Acceptance Criteria

- [ ] Title is displayed from Create Bill Page Form
- [ ] Total Amount is displayed Create Bill Page Form
- [ ] Participants are displayed Create Bill Page Form
- [ ] Paid by is displayed with user who paid Create Bill Page Form
- [ ] How much is owed is displayed with rest of participant(s)
- [ ] Add New Bill button is displayed

## Tasks

- [ ] write a function to calculate the split amount of any given number with the amount of participants.
- [ ] add a header with the input of title
- [ ] add a container showcasing the input of amount
- [ ] create participants component:
   - [ ] one is selected paid by
   - [ ] the other(s) show calculated split amount that is owed
- [ ] create button to add bill  
- [ ] button will create list item in Activity Page

## Complexity

... L

**Comment by AGeck113** [comment]
Hi Danie, i have a question to your US. I wasn't sure, if that should be a page that displays the data you entered before, or if that should be a form? 
I looked at your project and found the last US, where you add the data, so i know now, that it should just display something. Could you implement something in this US, to make clear, where the data comes from? Maybe something like "The page/component should display the data, based on the input from...." 
But overall it looks good to me :)

**Comment by d-opri** [comment]
> Hi Danie, i have a question to your US. I wasn't sure, if that should be a page that displays the data you entered before, or if that should be a form? I looked at your project and found the last US, where you add the data, so i know now, that it should just display something. Could you implement something in this US, to make clear, where the data comes from? Maybe something like "The page/component should display the data, based on the input from...." But overall it looks good to me :)

thanks! i updated it :)
